services:
    _defaults:
        autowire: false
        autoconfigure: false

    umanit_front_static_controller:
        class: Umanit\FrontBundle\Controller\StaticController
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: 'controller.service_arguments' }
            - { name: 'container.service_subscriber' }
        autoconfigure: true

    Umanit\FrontBundle\Controller\StaticController:
        alias: umanit_front_static_controller
        public: true

    umanit_front_init_command:
        class: Umanit\FrontBundle\Command\InitFrontCommand
        arguments:
            - '@file_locator'
            - '%kernel.project_dir%'
            -
                - assets
                - package.json
                - postcss.config.js
                - webpack.config.js
            -
                - assets/scss/styleguide
                - assets/scss/styleguide.scss
                - assets/js/styleguide.js
        tags: ['console.command']
