umanit_front_bundle.style_guide:
    path: /style-guide/{path}
    controller: Umanit\FrontBundle\Controller\StaticController
    defaults:
        basePath: 'style_guide/'
    requirements:
        path: .+

umanit_front_bundle.static_template:
    path: /static/{path}
    controller: Umanit\FrontBundle\Controller\StaticController
    defaults:
        basePath: ''
    requirements:
        path: .+
